ComplaintManagement/Models/UserMaster.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.EmployeeComplaintMasters = new HashSet<EmployeeComplaintMaster>();
        }
    
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeId { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string WorkEmail { get; set; }
        public string TimeType { get; set; }
        public int BusinessTitle { get; set; }
        public int Company { get; set; }
        public int LOSId { get; set; }
        public int SBUId { get; set; }
        public int SubSBUId { get; set; }
        public int CompentencyId { get; set; }
        public int LocationId { get; set; }
        public int RegionId { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string MobileNo { get; set; }
        public string Manager { get; set; }
        public string Type { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ImagePath { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public string empguid { get; set; }
    
        public virtual CompetencyMaster CompetencyMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeComplaintMaster> EmployeeComplaintMasters { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        public virtual LOSMaster LOSMaster { get; set; }
        public virtual RegionMaster RegionMaster { get; set; }
        public virtual SBUMaster SBUMaster { get; set; }
        public virtual SubSBUMaster SubSBUMaster { get; set; }
    }
}

ComplaintManagement/Controllers/UserMasterController.cs
using ComplaintManagement.Helpers;
using ComplaintManagement.Repository;
using ComplaintManagement.ViewModel;
using Elmah;
using Newtonsoft.Json;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ComplaintManagement.Controllers
{
    [Authorize]
    public class UserMasterController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            var DataTableDetail = new HomeController().getDataTableDetail("User", null);
            ViewBag.lstUser = JsonConvert.SerializeObject(GetAll(1));
            ViewBag.Page = DataTableDetail.Item1;
            ViewBag.PageIndex = DataTableDetail.Item2;
            return View();

        }
        [HttpGet]
        public ActionResult HistoryIndex(String id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                id = CryptoEngineUtils.Decrypt(id.Replace(" ", "+"), true);

                var lst = GetAllHistory(1, Convert.ToInt32(id));
                ViewBag.name = id.ToString();
                var DataTableDetail = new HomeController().getDataTableDetail("User", null);
                ViewBag.lstUserHistory = JsonConvert.SerializeObject(lst);
                ViewBag.Page = DataTableDetail.Item1;
                ViewBag.PageIndex = DataTableDetail.Item2;
                return View();
            }
            else
            {
                return View("Index");
            }

        }
        public ActionResult SearchUser(string search)
        {
            var originalList = GetAll(0);
            dynamic output = new List<dynamic>();

            foreach (var item in originalList)
            {
                var itemIndex = (IDictionary<string, object>)item;
                foreach (var kvp in itemIndex)
                {
                    if (kvp.Value != null)
                    {
                        if (kvp.Value.ToString().ToLower().Contains(search.ToLower()))
                        {
                            output.Add(item);
                        }
                        if (kvp.Key.ToString() == Messages.Status.ToString() && (search.ToLower() == Messages.Active.ToLower() || search.ToLower() == Messages.Inactive.ToLower()))
                        {
                            bool Status = Convert.ToBoolean(kvp.Value);
                            if (Status && search.ToLower() == Messages.Active.ToLower())
                            {
                                output.Add(item);
                            }
                            if (!Status && search.ToLower() == Messages.Inactive.ToLower())
                            {
                                output.Add(item);
                            }
                        }
                    }
                }
            }

            List<dynamic> data = output;
            ViewBag.lstUser = JsonConvert.SerializeObject(data.Distinct().ToList());

            return View("Index");
        }

        [HttpGet]
        public ActionResult LoadUserMasters(int currentPageIndex, string range = "")
        {
            ViewBag.lstUser = JsonConvert.SerializeObject(GetAll(currentPageIndex, range));
            if (!string.IsNullOrEmpty(range))
            {
                ViewBag.startDate = range.Split(',')[0];
                ViewBag.toDate = range.Split(',')[1];
            }
            return View("Index");
        }
        [HttpGet]
        public ActionResult LoadHistoryUserMasters(int currentPageIndex, int range = 0)
        {
            ViewBag.lstUserHistory = JsonConvert.SerializeObject(GetAllHistory(currentPageIndex, range));
            //if (!string.IsNullOrEmpty(range))
            //{
            //    ViewBag.startDate = range.Split(',')[0];
            //    ViewBag.toDate = range.Split(',')[1];
            //}
            return View("HistoryIndex");
        }

        public dynamic GetAll(int currentPage, string range = "")
        {
            int maxRows = 10; int lstCount = 0;
            if (currentPage == 0)
            {
                maxRows = 2147483647;
            }
            var lst = new UserMastersRepository().GetAll().ToList();
            lstCount = lst.Count;
            if (!string.IsNullOrEmpty(range))
            {
                string[] dates = range.Split(',');
                DateTime fromDate = Convert.ToDateTime(dates[0]);
                DateTime toDate = Convert.ToDateTime(dates[1]);
                lst = (from user in lst
                       where user.CreatedDate.Date >= fromDate.Date && user.CreatedDate.Date <= toDate.Date
                       select user).ToList();
                lstCount = lst.Count;
                lst = (lst)
                        .OrderByDescending(customer => customer.Id)
                        .Skip((currentPage - 1) * maxRows)
                        .Take(maxRows).ToList();


                dynamic output = new List<dynamic>();

                #region Other logics
                var lstSBU = new SBUMasterRepository().GetAll();
                var lstSubSBU = new SubSBUMasterRepository().GetAll();
                var lstLOS = new LOSMasterRepository().GetAll();
                var lstCompetency = new CompetencyMastersRepository().GetAll();
                var lstRegion = new RegionMasterRepository().GetAll();
                var lstDesignation = new DesignationMasterRepository().GetAll();
                var LstCompany = new EntityMasterRepository().GetAll();
                if (lst != null && lst.Count > 0)
                {
                    foreach (UserMasterVM com in lst)
                    {
                        dynamic row = new ExpandoObject();
                        if (com.SBUId > 0)
                        {
                            row.SBU = lstSBU.FirstOrDefault(x => x.Id == com.SBUId) != null ? lstSBU.FirstOrDefault(x => x.Id == com.SBUId).SBU : "";
                        }
                        if (com.SubSBUId > 0)
                        {

                            row.SubSBU = lstSubSBU.FirstOrDefault(x => x.Id == com.SubSBUId) != null ? lstSubSBU.FirstOrDefault(x => x.Id == com.SubSBUId).SubSBU : "";
                        }
                        if (com.LOSId > 0)
                        {
                            row.LOS = lstLOS.FirstOrDefault(x => x.Id == com.LOSId) != null ? lstLOS.FirstOrDefault(x => x.Id == com.LOSId).LOSName : "";
                        }
                        if (com.CompentencyId > 0)
                        {
                            row.Competency = lstCompetency.FirstOrDefault(x => x.Id == com.CompentencyId) != null ? lstCompetency.FirstOrDefault(x => x.Id == com.CompentencyId).CompetencyName : "";
                        }
                        if (com.RegionId > 0)
                        {
                            row.Region = lstRegion.FirstOrDefault(x => x.Id == com.RegionId) != null ? lstRegion.FirstOrDefault(x => x.Id == com.RegionId).Region : "";
                        }
                        if (com.BusinessTitle > 0)
                        {
                            row.BusinessTitle = lstDesignation.FirstOrDefault(x => x.Id == com.BusinessTitle) != null ? lstDesignation.FirstOrDefault(x => x.Id == com.BusinessTitle).Designation : "";
                        }
                        if (com.Company > 0)
                        {
                            row.Company = LstCompany.FirstOrDefault(x => x.Id == com.Company) != null ? LstCompany.FirstOrDefault(x => x.Id == com.Company).EntityName : "";
                        }
                        row.Id = com.Id;
                        row.EmployeeName = com.EmployeeName;
                        row.Status = com.Status;
                        row.TimeType = com.TimeType;
                        row.Manager = com.Manager;
                        row.CreatedByName = com.CreatedByName;
                        row.UpdatedByName = com.UpdatedByName;

                        row.UpdatedDate = com.UpdatedDate; row.CreatedDate = com.CreatedDate;

                        output.Add(row);
                    }
                }

                #endregion

                double pageCount = (double)((decimal)lstCount / Convert.ToDecimal(maxRows));
                ViewBag.PageCount = (int)Math.Ceiling(pageCount);

                ViewBag.CurrentPageIndex = currentPage;
                return output;
            }
            else
            {

                dynamic output = new List<dynamic>();

                lst = (from user in lst
                       select user)
           .OrderByDescending(user => user.Id)
           .Skip((currentPage - 1) * maxRows)
           .Take(maxRows).ToList();

                #region Other joining logics
                var lstSBU = new SBUMasterRepository().GetAll();
                var lstSubSBU = new SubSBUMasterRepository().GetAll();
                var lstLOS = new LOSMasterRepository().GetAll();
                var lstCompetency = new CompetencyMastersRepository().GetAll();
                var lstRegion = new RegionMasterRepository().GetAll();
                var lstDesignation = new DesignationMasterRepository().GetAll();
                var LstCompany = new EntityMasterRepository().GetAll();
                if (lst != null && lst.Count > 0)
                {
                    foreach (UserMasterVM com in lst)
                    {
                        dynamic row = new ExpandoObject();
                        if (com.SBUId > 0)
                        {
                            row.SBU = lstSBU.FirstOrDefault(x => x.Id == com.SBUId) != null ? lstSBU.FirstOrDefault(x => x.Id == com.SBUId).SBU : "";

                        }
                        if (com.SubSBUId > 0)
                        {

ComplaintManagement/Views/UserMaster/HistoryIndex.cshtml
@using ComplaintManagement.Helpers
@using System
@using System.Globalization
@{
    var user = ""; var userImage = string.Empty;
    int userId = 0;
    var claimsIdentity = User.Identity as System.Security.Claims.ClaimsIdentity;

    if (claimsIdentity != null)
    {
        var c = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.Name);
        var cI = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.UserData);
        var userIDInfo = claimsIdentity.FindFirst(System.Security.Claims.ClaimTypes.Sid);

        if (c != null && cI != null && userIDInfo != null)
        {

            user = c.Value.ToString();
            userImage = cI.Value.ToString();
            userId = Convert.ToInt32(userIDInfo.Value.ToString());
        }
    }
    ViewBag.Title = "User master histories";
    dynamic data = Json.Decode(ViewBag.lstUserHistory);
}
<!-- Page Wrapper -->
@Html.Hidden("history", (object)ViewBag.name)

<!-- Content Wrapper -->

        <!-- Begin Page Content -->
        <a href="/UserMaster/Index" class="btn btn-danger ml-4">&laquo; Back</a> <br /><br />
      
            <div class="preloader"></div>
            <div class="page-title">
                <h2 class="text-black">User History</h2>
            </div>
            <div class="card mb-4 rounded-0 border-0">
                <div class="card-body">
                    <div class="row justify-content-between">
                        <div class="col-md-8">
                            <ul class="nav">
                                <li class="nav-item">
                                    <button type="button" class="btn btn-danger rounded-circle h-40p w-40p" onclick="location.href='@Url.Action("ExportDataHistory", "UserMaster", new {id = ViewBag.name})'" data-toggle="tooltip" data-placement="top" title="Excel"><i class="fas fa-file-excel"></i></button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Tab Bar -->
            <div class="user-list">
                <div class="row">
                    <div class="col-xl-12 col-lg-12">
                        <div class="card mb-4 rounded-0 border-0">
                            <!-- Card Body -->
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table f-14" id="myTable">
                                        <thead>
                                            <tr>
                                                <td>Employee Name</td>
                                                <td>Created Date</td>
                                                @*   <td>Created By</td>*@
                                                @*<td>Modified Date</td>*@
                                                @* <td>Modified By</td>*@
                                                <td>Status</td>
                                                <td>Created By</td>
                                                <td>Time Type</td>
                                                <td>Business Title</td>
                                                <td>Entity State</td>
                                                <td>Company</td>
                                                <td>LOS</td>
                                                <td>SBU</td>
                                                <td>Sub-SBU</td>
                                                <td>Competency</td>
                                                <td>Region</td>
                                                <td>Manager</td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in data)
                                            {
                                                <tr>
                                                    <td class="text-black text-center"><strong>@item.EmployeeName</strong></td>
                                                    <td class="text-black text-center">
                                                        <strong>
                                                            @if (item.CreatedDate != null)
                                                            {
                                                                var date = String.Format("{0}", item.CreatedDate.Substring(0, item.CreatedDate.IndexOf("T")).Replace("-", "/")).ToString();
                                                                @Html.Raw(DateTime
                                                            .ParseExact(date, "yyyy/MM/dd", CultureInfo.InvariantCulture)
                                                            .ToString("dd/MM/yyyy", CultureInfo.InvariantCulture));
                                                            }
                                                        </strong>
                                                    </td>
                                                    @*<td class="text-black text-center"><strong>@item.CreatedByName</strong></td>*@
                                                    @*<td class="text-black text-center">
                                                            <strong>
                                                                @if (item.UpdatedDate != null)
                                                                {
                                                                    @Html.Raw(String.Format("{0}", item.UpdatedDate.Substring(0, item.UpdatedDate.IndexOf("T"))))
                                                                }
                                                                else
                                                                {
                                                                    @Html.Raw(Messages.NotAvailable.ToString())
                                                                }
                                                            </strong>
                                                        </td>*@
                                                    @*<td class="text-black text-center"><strong>@item.UpdatedByName</strong></td>*@
                                                    <td class="text-black text-center">
                                                        <strong>
                                                            @if (item.Status == true)
                                                            {@Html.Raw("Active") }
                                                        else
                                                        { @Html.Raw("Inactive")}
                                                        </strong>
                                                    </td>
                                                    <td class="text-black text-center pl-2"><strong>@item.CreatedByName</strong></td>

                                                    <td class="text-black text-center"><strong>@item.TimeType</strong></td>
                                                    <td class="text-black text-center"><strong>@item.BusinessTitle</strong></td>
                                                    <td class="text-black text-center"><strong>@item.EntityState</strong></td>
                                                    <td class="text-black text-center"><strong>@item.Company</strong></td>
                                                    <td class="text-black text-center"><strong>@item.LOS</strong></td>
                                                    <td class="text-black text-center"><strong>@item.SBU</strong></td>
                                                    <td class="text-black text-center"><strong>@item.SubSBU</strong></td>
                                                    <td class="text-black text-center"><strong>@item.Competency</strong></td>
                                                    <td class="text-black text-center"><strong>@item.Region</strong></td>
                                                    <td class="text-black text-center"><strong>@item.Manager</strong></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                                <br />
                                <table class="float-right" id="paginator" cellpadding="0" cellspacing="0">
                                    <tr>
                                        @for (int i = 1; i <= ViewBag.PageCount; i++)
                                        {
                                            <td>
                                                <div class="pagination">
                                                    @if (i != ViewBag.CurrentPageIndex)
                                                    {
                                                        <a href="javascript:PagerClick(@i);">@i</a>
                                                    }
                                                    else
                                                    {
                                                        <span>@i</span>
                                                    }
                                                </div>
                                            </td>
                                        }
                                    </tr>
                                </table>
                                <input type="hidden" id="hfCurrentPageIndex" name="currentPageIndex" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!-- /.container-fluid -->
   
<!-- End of Content Wrapper -->
<div class="modal" tabindex="-1" id="uploadFile">
    <div class="modal-dialog modal-lg">
        <div class="modal-content border-0 rounded-0">
            <span class="close-modal" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </span>
            <div class="modal-body">
                <label class="d-block file-upload mb-3">Upload File</label>
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" onclick="this.value = null" class="custom-file-input" id="excelFile" data-ketan="" aria-describedby="inputGroupFileAddon01">
                                    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <a class="btn btn-danger btn-user btn-sm" id="btnUpload">Upload</a>
                        <a href="/UserMaster/Index" class="btn bg-white border btn-user btn-sm">Cancel</a>
                    </div>
                    <a href="/Files/DownloadFile?filePath=/Imports/Samples/User/Users.xlsx" class="ml-3 mt-n2">Download Sample</a>
                    <label id="lblError" class="ml-n5 mt-5 adderror"></label>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End of Page Wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
@Html.Partial("_CommonDeleteModal")
<script>
    var pageLength=@ViewBag.PageIndex;
    var page = @ViewBag.Page;
</script>